name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore src/EchoesGame

      - name: Build
        run: dotnet build src/EchoesGame -c Release --no-restore

      - name: Publish (win-x64)
        run: dotnet publish src/EchoesGame -c Release -r win-x64 --self-contained false -o build/win-x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EchoesOfTheLastStar-win-x64
          path: build/win-x64
