name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish (win-x64)
        run: |
          dotnet restore src/EchoesGame
          dotnet publish src/EchoesGame -c Release -r win-x64 --self-contained false -o build/win-x64
          powershell -Command "Compress-Archive -Path build/win-x64/* -DestinationPath build/EchoesOfTheLastStar-win-x64.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/EchoesOfTheLastStar-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
